volumes:
    postgres-data:
    redis-data:

networks:
    crm-network:

name: "crm"

services:
    php:
        container_name: crm-php
        ports:
            - "8021:80"
        build:
            context: ..
            dockerfile: .docker/php/Dockerfile
        volumes:
            - ../:/var/www/app
            - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/crm-php.ini
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - crm-network
        depends_on:
            - postgres
            - redis

    postgres:
        container_name: crm-db
        image: postgres:16.0
        ports:
            - "127.0.0.1:5470:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: 'crm-db'
            POSTGRES_USER: 'user'
        restart: always
        networks:
            - crm-network

    redis:
        container_name: crm-redis
        image: redis:latest
        sysctls:
            - net.core.somaxconn=511
        volumes:
            - redis-data:/data
        networks:
            - crm-network
